### ISSUE TITLE
Vendor Module Issues

### ISSUE THREAD

**Issue by Obsurd** [ebonyfaye/Jamba#10]
Ok, briefly talked to you about this in Discord to make sure it was indeed a bug.  Custom groups when added to a tag, aren't working when it comes to vendoring items.  I have several setup across several teams and different groups, none of which work.  I add the item to 'all' and *poof* it goes.

Another issue I've found with it, is it doesn't always actually vendor soulband Epics set with in the threshold that it is set.  I had 1 toon in a set of all identical settings and not a single purple would sell after running old raids.  Noticed this on a few other teams through out the night.  I think it's because of the "2 hour trading" that they get and sometimes (not all the time) when trying to vendor an item that's tradeable, a confirmation window pops up asking if you're sure, because it'll make it soulbound and unable to be traded even if bought back.  And I think that window when it happens, is causing it not to sell any Epics until something is done manually to adjust that being maybe the first one Jamba decides to sell or something.  I dunno, just a guess here.

**Comment by ebonyfaye** [comment]
ya ill try and sort this out this week some time

**Comment by ebonyfaye** [comment]
hi, i just checked sell: list and it seems to work with groups i setup a group added the char to group and it sold the stuff, and then i did removed it from the group and it did not sell the item. did you add the chars in the right group??

as for the selling items witch can be traded that going to need some extra work so am not sure when i can get around to fixing that

**Comment by Obsurd** [comment]
I literally just tried it.  My character is IN the "Conqueror" group.  I have 6 different things in my inventory set to sell in that group.  Open vendor, nothing happens.  

I removed the character from the group and tried.  Nothing (like it's supposed to anyways).
I re-add the character to the group and tried.  Nothing.  
I then add an item to the 'all' tag and tried.  POOOOOF
I then add an item to the 'deahtknight' tag and tried.  POOOOOF

It works with Jamba created groups.  But with custom generated ones, not so much.

**Comment by ebonyfaye** [comment]
hi i have found the bug it is case sensitive.

it should of not of yet you put in a case sensitive Groups, but some reason the code was using the wrong string.

should be fixed in 75 

As well you should be able to remove old case sensitive Groups. 

You might need to Re add the groups again them for them to work.

hope this helps!

**Comment by Obsurd** [comment]
Yay!  Great job!

**Comment by ebonyfaye** [comment]
Did it work for you then? Let me know so i can close the ticket after u tested ot

**Comment by ebonyfaye** [comment]
well am not classing that as a bug its more of "blizzard" Q am not sure but i think we open that as a new problem.
