### ISSUE TITLE
"Space for Name" in currency settings

### ISSUE THREAD

**Issue by Jabberie** [ebonyfaye/Jamba#8]
![image](https://user-images.githubusercontent.com/18558639/42423418-9aa53e64-82f1-11e8-95fa-aadf1ea14e8f.png)

**Comment by Jabberie** [comment]
Yes Space for Gold

**Comment by ebonyfaye** [comment]
L["SPACE_FOR_NAME"] = "Space For Name"
L["SPACE_FOR_GOLD"] =  "Space For Name" 

think i see the problem
